service: dlt-workpass-telegram-bot

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  environment:
    BOT_API_KEY: ${env:BOT_API_KEY}
    CHANNEL_ID: ${env:TARGET_CHANNEL_ID}

functions:
  sendTestMessage:
    handler: handler.sendTestMessage
    events:
      - http:
          path: /post/testmessage
          method: post
  getRequirement:
    handler: handler.getRequirement
    events:
      - http:
          path: /get/requirements
          method: get
  postRequirement:
    handler: handler.postRequirement
    events:
      - http:
          path: /post/requirements
          method: post

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
